### ISSUE TITLE
Fully mock MetaMask

### ISSUE THREAD

**Issue by talentlessguy** [VGLoic/eth-testing#41] opened 2022-05-04 19:44 UTC
### What is the new or updated feature that you are suggesting?

Would be awesome if `testingUtils.getProvider()` would return an EIP-1193 compatible provider.

Here is a mock provider which could be used:

https://github.com/NoahZinsmeister/web3-react/blob/f8e5531f8facb53d7cb35165d1878db284c24736/packages/eip1193/src/index.spec.ts#L20

### Why should this feature be included?

When testing code based on web3-react, it actively uses the `Web3Provider` to add even listeners and make RPC requests.

**Comment by VGLoic** [comment] 2022-05-06 07:27
Hey @talentlessguy! Thanks a lot for the issue!

So the current provider should implement quite closely the interface of an EIP-1193 provider, i.e. the `request` and the events part. Thanks to your link, I'm trying to migrate the event handling part to EventEmitter from node directly in order to be fully ok with EIP-1193 on this side (wip PR [here](#42) :)

However, the provider is not functionally implementing the EIP-1193 specs intentionally as the goal is to let the developer mocks the way she/he wants the RPC requests and emit the needed events on demand. 

I don't think I can return the mock provider of `web3-react`, the events emitting and listening are similar in both provider (once my update PR has been merged at least ahah), however the implementation of the `request` method is different. In the case of the mock of `web3-react`, only some RPC methods are mocked using local state while in the approach of this lib, we register mocks of any RPC method

However, to be honest, I have not tried the library with `web3-react` so I definitely need to do so in order to check if something is not working as intended 😅

**Comment by VGLoic** [comment] 2022-07-21 12:28
Closing this issue as `web3-react` is now supported from #48 

Reopen if any issues occur!

**Closed by VGLoic** 2022-07-21 12:28 UTC
